### ISSUE TITLE
Add CLI extension support

### ISSUE THREAD

**Issue by ananthdurai** [recap-cloud/recap#51]
Can the extension framework [like hooks] be added along with the rest and the cli interface? Something like `Recap` as a microkernel with a plugin-style system. One possible extension is generating a static website from the Recap metadata [like dbt docs], which can be reused by many.

**Comment by criccomini** [comment]
This is a great idea. It should be doable. I need to do a bit of research to figure out the right way to do this in Python. IIRC, `dbt` has a similar style. It would be nice if there was some open source library that made extension management easy.

**Comment by criccomini** [comment]
So, I sniffed around `dbt` a bit. They have [adapters](https://docs.getdbt.com/guides/dbt-ecosystem/adapter-development/1-what-are-adapters), which are much more limited in scope than the extensions we're talking about. They also have [packages](https://docs.getdbt.com/docs/build/packages), which looks more like what I was thinking. But packages seem to be `dbt` projects rather than raw Python code.

What I really want is just a Python library that someone can write and publish. If the library has classes that implement Recap abstract classes, then the library's functionality automatically become available in Recap. To make Recap aware, it'd either have to crawl all packages in PYTHONPATH, or developers would have to update a config variable to tell Recap what's available.

Some relevant links:

* https://hub.getdbt.com - Where packages are published.
* https://docs.getdbt.com/guides/legacy/building-packages - How to write a `dbt` package.

**Comment by criccomini** [comment]
I'm starting to poke around Python plugin libraries, which seem useful. There are a bunch of options, but [pluggy](https://github.com/pytest-dev/pluggy/) looks the most mature. I'm not sure how much value it adds over implementing my own:

* https://packaging.python.org/en/latest/guides/creating-and-discovering-plugins/
* https://alysivji.github.io/simple-plugin-system.html

I'm in favor of Implementing my own plugin architecture, and following the packaging.python.org guide. It seems fairly straight forward. The main thing is making sure I have the right abstractions in Recap, something I'm still iterating on.

**Comment by ananthdurai** [comment]
The airflow plugin architecture is also an interesting approach, though they do not support cli extension, but does API extension. 
https://airflow.apache.org/docs/apache-airflow/stable/plugins.html

**Comment by criccomini** [comment]
I sniffed around the Airflow plugin system a bit. It looks to me like it's essentially just doing option (3) in the packaging.python.org guide--setuptools entrypoints. This was already the direction I was leaning, so Airflow's usage further validates my inclination. :)

**Comment by criccomini** [comment]
Added @ananthdurai! Thanks for the idea. See:

https://github.com/recap-cloud/recap/pull/52

For some docs.
